name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 8.1.1
publish_to: none
repository: https://github.com/fluttercandies/extended_image
issue_tracker: https://github.com/fluttercandies/extended_image/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  extended_image_library:
    git: https://github.com/kumsumit/extended_image_library.git
  flutter:
    sdk: flutter
  meta: ^1.16.0
dev_dependency:
  lints: ^5.0.0
